services:
  mysite:
    container_name: mysite
    image: ${DOCKER_REGISTRY}/mysite
    ports:
      - "34664:8080"
      - "34665:8081"
    depends_on:
      - mysiteapi
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  mysiteapi:
    container_name: mysite-api
    image: ${DOCKER_REGISTRY}/mysite-api
    ports:
      - "34666:8080"
      - "34667:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/drive/TweetScreenshots
    restart: always
